### ISSUE TITLE
Another flavour of Candyscript

### ISSUE THREAD

**Issue by benob** [divy-work/candyscript#1]
I created a fork of CandyScript which does a bit more.
https://github.com/benob/candyscript/

It would probably be too much for a PR, but I though you might like it. Let me know if you have ideas on how the different features should be implemented in the language.

**Comment by littledivy** [comment]
Looks really cool! Perhaps, would you like me to redirect users from the README of this repo?

**Comment by benob** [comment]
I don't want to look like I stole your idea. So feel free to do as you want.
